server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ptproject
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
